//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COBOAM_Admin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COBOAM_Admin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs for {0}.
        /// </summary>
        public static string Activity_No_Logs {
            get {
                return ResourceManager.GetString("Activity_No_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement &quot;{0}&quot; created..
        /// </summary>
        public static string Announcements_Created {
            get {
                return ResourceManager.GetString("Announcements_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title..
        /// </summary>
        public static string Announcements_Need_Title {
            get {
                return ResourceManager.GetString("Announcements_Need_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement &quot;{0}&quot; updated..
        /// </summary>
        public static string Announcements_Updated {
            get {
                return ResourceManager.GetString("Announcements_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devotion added for {0}/{1}.
        /// </summary>
        public static string Devotion_Added {
            get {
                return ResourceManager.GetString("Devotion_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devotion deleted for {0}/{1}.
        /// </summary>
        public static string Devotion_Deleted {
            get {
                return ResourceManager.GetString("Devotion_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a quote..
        /// </summary>
        public static string Devotion_Need_Quote {
            get {
                return ResourceManager.GetString("Devotion_Need_Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a scripture..
        /// </summary>
        public static string Devotion_Need_Scripture {
            get {
                return ResourceManager.GetString("Devotion_Need_Scripture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devotion updated for {0}/{1}..
        /// </summary>
        public static string Devotion_Updated {
            get {
                return ResourceManager.GetString("Devotion_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter text..
        /// </summary>
        public static string General_Need_Text {
            get {
                return ResourceManager.GetString("General_Need_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.....
        /// </summary>
        public static string LB_Create_New {
            get {
                return ResourceManager.GetString("LB_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete Announcement &quot;{0}&quot;?.
        /// </summary>
        public static string MB_Announcements_Delete {
            get {
                return ResourceManager.GetString("MB_Announcements_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string MB_Caption_Error {
            get {
                return ResourceManager.GetString("MB_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string MB_Confirmation {
            get {
                return ResourceManager.GetString("MB_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file cannot be found. Would you like to create it now?.
        /// </summary>
        public static string MB_Show_Config {
            get {
                return ResourceManager.GetString("MB_Show_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server.  Contact administrator.
        /// </summary>
        public static string Mysql_1042 {
            get {
                return ResourceManager.GetString("Mysql_1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password, please try again.
        /// </summary>
        public static string Mysql_1045 {
            get {
                return ResourceManager.GetString("Mysql_1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
